runtime: python311

entrypoint: gunicorn -b :$PORT env_protect_game.wsgi:application

handlers:
- url: .*
  secure: always
  script: auto

- url: /static
  static_dir: static/

runtime_config:
    operating_system: "ubuntu22"

