runtime: python311

handlers:
- url: /.*
  script: auto
  secure: always

- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico
  secure: always

entrypoint: gunicorn -b :$PORT env_protect_game.wsgi:application
